services:
  - type: web
    name: katarunganhub-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: SEMAPHORE_API_KEY
        sync: false
      - key: SEMAPHORE_SENDER_NAME
        sync: false
